apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 329599636493.dkr.ecr.ap-south-1.amazonaws.com/b12:545816c7545a13f00748fce5f8543772c75214b3
          ports:
            - containerPort: 3000
